"""
OT-2 NLP Agent - FastAPI Test Server

Supports both traditional instruction-based workflow and the new Planner/Compiler architecture.
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

from ot2_agent import OT2Agent

# Import Planner/Compiler
from ot2_agent.planner import Planner, PlannerOutput, WorkflowDraft, ConfirmedWorkflow
from ot2_agent.compiler import Compiler, CompilerOutput
from ot2_agent.planner.domain_knowledge import OERDomainKnowledge
from ot2_agent.compiler.device_mapper import DeviceRegistry

app = FastAPI(
    title="OT-2 NLP Agent API",
    description="Natural language interface for Opentrons OT-2 robot with Planner/Compiler support",
    version="2.0.0"
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global instances
agent = OT2Agent()
planner = Planner(OERDomainKnowledge())
compiler = Compiler(DeviceRegistry())


# ============ Request/Response Models ============

class ParseRequest(BaseModel):
    instruction: str

class ParseResponse(BaseModel):
    operation: Optional[str]
    params: dict
    confidence: float
    language: str

class LabwareRequest(BaseModel):
    labware_type: str
    slot: int
    name: Optional[str] = None

class PipetteRequest(BaseModel):
    pipette_type: str
    mount: str
    tip_rack: Optional[str] = None

class ProtocolRequest(BaseModel):
    name: str
    description: str = ""
    labware: List[LabwareRequest] = []
    pipettes: List[PipetteRequest] = []
    instructions: List[str] = []

class ProtocolResponse(BaseModel):
    preview: str
    validation: str
    is_valid: bool
    code: str


# ============ Planner/Compiler Models ============

class MissingInfoResponse(BaseModel):
    """Information about a missing parameter."""
    parameter: str
    question: str
    question_zh: str
    options: Optional[List[str]] = None
    default: Optional[Any] = None
    required: bool = True


class UnitOperationResponse(BaseModel):
    """A unit operation in a workflow."""
    name: str
    uo_type: str
    description: str
    parameters: Dict[str, Any]
    placeholders: List[MissingInfoResponse]


class WorkflowCandidateResponse(BaseModel):
    """A candidate workflow generated by the planner."""
    name: str
    description: str
    confidence: float
    unit_operations: List[UnitOperationResponse]
    assumptions: List[str]
    alternatives: List[str]


class IntentResponse(BaseModel):
    """Parsed intent from user input."""
    goal: str
    domain: str
    language: str
    confidence: float
    target_metrics: List[str]
    known_conditions: Dict[str, Any]


class PlanRequest(BaseModel):
    """Request to plan an experiment."""
    intent: str = Field(..., description="Natural language description of the experiment")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Known conditions and constraints")


class PlanResponse(BaseModel):
    """Response from the planner."""
    intent: IntentResponse
    candidates: List[WorkflowCandidateResponse]
    recommended_idx: int


class CompileRequest(BaseModel):
    """Request to compile a workflow."""
    candidate_index: int = Field(..., description="Index of the candidate workflow to compile")
    filled_parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters filled in by the user")
    # The workflow candidates must be passed from a previous /plan call
    # In a real app, you might store them in a session or pass them directly


class ValidationIssueResponse(BaseModel):
    """A validation issue."""
    severity: str
    message: str
    step: Optional[str] = None


class CheckpointResponse(BaseModel):
    """A human checkpoint in the workflow."""
    step_index: int
    step_name: str
    message: str
    message_zh: str
    is_critical: bool


class CompileResponse(BaseModel):
    """Response from the compiler."""
    is_valid: bool
    error_count: int
    warning_count: int
    issues: List[ValidationIssueResponse]
    checkpoints: List[CheckpointResponse]
    python_code: str
    workflow_json: str


class PlanAndCompileRequest(BaseModel):
    """Combined request to plan and compile in one step."""
    intent: str = Field(..., description="Natural language description of the experiment")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Known conditions and constraints")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters to fill in")
    candidate_index: int = Field(default=0, description="Which candidate to use (0 = recommended)")


# ============ Endpoints ============

@app.get("/")
def root():
    return {
        "service": "OT-2 NLP Agent",
        "version": "2.0.0",
        "status": "running",
        "endpoints": {
            "legacy": [
                "POST /parse        - Parse single instruction",
                "POST /protocol     - Create full protocol",
                "GET  /operations   - List supported operations",
                "GET  /labware      - List labware aliases",
                "GET  /pipettes     - List pipette aliases",
            ],
            "planner_compiler": [
                "POST /plan         - Plan experiment from intent",
                "POST /compile      - Compile workflow candidate",
                "POST /plan-compile - Plan and compile in one step",
                "GET  /templates    - List available UO templates",
            ]
        }
    }


@app.post("/parse", response_model=ParseResponse)
def parse_instruction(request: ParseRequest):
    """Parse a natural language instruction."""
    intent = agent.parse(request.instruction)
    return ParseResponse(
        operation=intent.operation_type.value if intent.operation_type else None,
        params=intent.params,
        confidence=intent.confidence,
        language=intent.language
    )


@app.post("/protocol", response_model=ProtocolResponse)
def create_protocol(request: ProtocolRequest):
    """Create a complete protocol from configuration and instructions."""
    # Create protocol
    protocol = agent.create_protocol(
        name=request.name,
        description=request.description
    )

    # Add labware
    for lw in request.labware:
        agent.add_labware(protocol, lw.labware_type, lw.slot, lw.name)

    # Add pipettes
    for pip in request.pipettes:
        agent.add_pipette(protocol, pip.pipette_type, pip.mount, pip.tip_rack)

    # Add instructions
    for instruction in request.instructions:
        agent.add_instruction(protocol, instruction)

    # Validate
    validation = agent.validate(protocol)

    # Generate
    preview = agent.preview(protocol)
    code = agent.generate(protocol)

    return ProtocolResponse(
        preview=preview,
        validation=str(validation),
        is_valid=validation.is_valid,
        code=code
    )


@app.get("/operations")
def list_operations():
    """List all supported operations with keywords."""
    from ot2_agent.operations import OperationMapper
    mapper = OperationMapper()
    return {
        op_type.value: keywords
        for op_type, keywords in mapper.KEYWORDS.items()
    }


@app.get("/labware")
def list_labware():
    """List all labware aliases."""
    from ot2_agent.operations import OperationMapper
    mapper = OperationMapper()
    return mapper.LABWARE_ALIASES


@app.get("/pipettes")
def list_pipettes():
    """List all pipette aliases."""
    from ot2_agent.operations import OperationMapper
    mapper = OperationMapper()
    return mapper.PIPETTE_ALIASES


# ============ Planner/Compiler Endpoints ============

# Store last planning result for compile endpoint
_last_plan_output: Optional[PlannerOutput] = None


@app.post("/plan", response_model=PlanResponse)
def plan_experiment(request: PlanRequest):
    """
    Plan an experiment from a natural language intent.

    Returns candidate workflows with missing parameters that need to be filled.
    Use the /compile endpoint to compile a selected candidate.
    """
    global _last_plan_output

    try:
        output = planner.plan(request.intent, request.context)
        _last_plan_output = output

        # Convert to response models
        candidates = []
        for candidate in output.candidates:
            uos = []
            for uo in candidate.unit_operations:
                placeholders = [
                    MissingInfoResponse(
                        parameter=name,
                        question=info.question,
                        question_zh=info.question_zh,
                        options=info.options,
                        default=info.default,
                        required=info.required
                    )
                    for name, info in uo.placeholders.items()
                ]
                uos.append(UnitOperationResponse(
                    name=uo.name,
                    uo_type=uo.uo_type.value,
                    description=uo.description,
                    parameters=uo.parameters,
                    placeholders=placeholders
                ))

            candidates.append(WorkflowCandidateResponse(
                name=candidate.name,
                description=candidate.description,
                confidence=candidate.confidence,
                unit_operations=uos,
                assumptions=candidate.assumptions,
                alternatives=candidate.alternatives
            ))

        return PlanResponse(
            intent=IntentResponse(
                goal=output.intent.goal,
                domain=output.intent.domain,
                language=output.intent.language,
                confidence=output.intent.confidence,
                target_metrics=output.intent.target_metrics,
                known_conditions=output.intent.known_conditions
            ),
            candidates=candidates,
            recommended_idx=output.recommended_idx
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/compile", response_model=CompileResponse)
def compile_workflow(request: CompileRequest):
    """
    Compile a workflow candidate from a previous /plan call.

    Requires that /plan was called first to generate candidates.
    """
    global _last_plan_output

    if _last_plan_output is None:
        raise HTTPException(
            status_code=400,
            detail="No planning result available. Call /plan first."
        )

    if request.candidate_index < 0 or request.candidate_index >= len(_last_plan_output.candidates):
        raise HTTPException(
            status_code=400,
            detail=f"Invalid candidate_index. Must be 0-{len(_last_plan_output.candidates)-1}"
        )

    try:
        # Get the selected candidate
        candidate = _last_plan_output.candidates[request.candidate_index]

        # Create confirmed workflow
        confirmed = ConfirmedWorkflow(
            draft=candidate,
            filled_parameters=request.filled_parameters
        )

        # Compile
        output = compiler.compile(confirmed)

        # Convert validation issues
        issues = [
            ValidationIssueResponse(
                severity=issue.severity,
                message=issue.message,
                step=issue.step
            )
            for issue in output.validation_result.issues
        ]

        # Convert checkpoints
        checkpoints = [
            CheckpointResponse(
                step_index=cp.step_index,
                step_name=cp.step_name,
                message=cp.message,
                message_zh=cp.message_zh,
                is_critical=cp.is_critical
            )
            for cp in output.validation_result.checkpoints
        ]

        return CompileResponse(
            is_valid=output.validation_result.is_valid,
            error_count=output.validation_result.error_count,
            warning_count=output.validation_result.warning_count,
            issues=issues,
            checkpoints=checkpoints,
            python_code=output.python_code,
            workflow_json=output.workflow_json
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/plan-compile", response_model=CompileResponse)
def plan_and_compile(request: PlanAndCompileRequest):
    """
    Plan and compile an experiment in one step.

    Combines /plan and /compile for convenience.
    """
    try:
        # Plan
        output = planner.plan(request.intent, request.context)

        if not output.candidates:
            raise HTTPException(
                status_code=400,
                detail="No workflow candidates could be generated for this intent."
            )

        # Select candidate
        idx = request.candidate_index
        if idx < 0 or idx >= len(output.candidates):
            idx = output.recommended_idx

        candidate = output.candidates[idx]

        # Create confirmed workflow
        confirmed = ConfirmedWorkflow(
            draft=candidate,
            filled_parameters=request.parameters
        )

        # Compile
        compile_output = compiler.compile(confirmed)

        # Convert to response
        issues = [
            ValidationIssueResponse(
                severity=issue.severity,
                message=issue.message,
                step=issue.step
            )
            for issue in compile_output.validation_result.issues
        ]

        checkpoints = [
            CheckpointResponse(
                step_index=cp.step_index,
                step_name=cp.step_name,
                message=cp.message,
                message_zh=cp.message_zh,
                is_critical=cp.is_critical
            )
            for cp in compile_output.validation_result.checkpoints
        ]

        return CompileResponse(
            is_valid=compile_output.validation_result.is_valid,
            error_count=compile_output.validation_result.error_count,
            warning_count=compile_output.validation_result.warning_count,
            issues=issues,
            checkpoints=checkpoints,
            python_code=compile_output.python_code,
            workflow_json=compile_output.workflow_json
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/templates")
def list_templates():
    """List all available UO templates."""
    from ot2_agent.templates import get_template_registry

    registry = get_template_registry()
    templates = registry.list_templates()

    result = {}
    for name in templates:
        template = registry.get_template(name)
        if template:
            result[name] = {
                "uo_type": template.uo_type.value,
                "description": template.description,
                "parameters": list(template.parameters.keys()),
                "placeholders": list(template.placeholders.keys()),
            }

    return result


@app.get("/missing-parameters")
def get_missing_parameters(intent: str, context: Optional[str] = None):
    """
    Get the missing parameters for a given intent.

    Useful for building forms to collect user input.
    """
    try:
        ctx = {}
        if context:
            import json
            ctx = json.loads(context)

        output = planner.plan(intent, ctx)

        if not output.candidates:
            return {"missing_parameters": []}

        # Get missing params from recommended candidate
        candidate = output.candidates[output.recommended_idx]
        missing = []

        for uo in candidate.unit_operations:
            for name, info in uo.placeholders.items():
                missing.append({
                    "parameter": name,
                    "question": info.question,
                    "question_zh": info.question_zh,
                    "options": info.options,
                    "default": info.default,
                    "required": info.required,
                    "uo_name": uo.name
                })

        return {"missing_parameters": missing}

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
