"""
Protocol Generator for OT-2 robot.
Converts operations to executable Python protocol files.
"""

import json
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from .operations import Operation, OperationType


@dataclass
class LabwareConfig:
    """Configuration for a labware item."""
    name: str
    labware_type: str
    slot: int


@dataclass
class PipetteConfig:
    """Configuration for a pipette."""
    name: str
    pipette_type: str
    mount: str  # 'left' or 'right'
    tip_rack: Optional[str] = None


@dataclass
class Protocol:
    """
    A complete OT-2 protocol.

    Contains all information needed to generate an executable protocol file.
    """
    name: str
    description: str = ""
    api_level: str = "2.13"
    author: str = "OT-2 NLP Agent"
    created_at: datetime = field(default_factory=datetime.now)

    # Configuration
    labware: List[LabwareConfig] = field(default_factory=list)
    pipettes: List[PipetteConfig] = field(default_factory=list)

    # Operations
    operations: List[Operation] = field(default_factory=list)

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)
    original_instructions: List[str] = field(default_factory=list)

    def add_labware(self, name: str, labware_type: str, slot: int):
        """Add labware to the protocol."""
        self.labware.append(LabwareConfig(name, labware_type, slot))

    def add_pipette(self, name: str, pipette_type: str, mount: str, tip_rack: str = None):
        """Add pipette to the protocol."""
        self.pipettes.append(PipetteConfig(name, pipette_type, mount, tip_rack))

    def add_operation(self, operation: Operation):
        """Add an operation to the protocol."""
        self.operations.append(operation)

    def to_dict(self) -> Dict[str, Any]:
        """Convert protocol to dictionary format."""
        return {
            "name": self.name,
            "description": self.description,
            "api_level": self.api_level,
            "author": self.author,
            "created_at": self.created_at.isoformat(),
            "labware": [
                {"name": lw.name, "type": lw.labware_type, "slot": lw.slot}
                for lw in self.labware
            ],
            "pipettes": [
                {
                    "name": pip.name,
                    "type": pip.pipette_type,
                    "mount": pip.mount,
                    "tip_rack": pip.tip_rack
                }
                for pip in self.pipettes
            ],
            "operations": [
                {
                    "type": op.type.value,
                    "params": op.params,
                    "description": op.description
                }
                for op in self.operations
            ],
            "original_instructions": self.original_instructions
        }


class ProtocolGenerator:
    """
    Generates executable OT-2 protocol files from Protocol objects.

    Example:
        generator = ProtocolGenerator()
        code = generator.generate(protocol)
        generator.save(protocol, "my_protocol.py")
    """

    PROTOCOL_TEMPLATE = '''"""
{name}

{description}

Generated by OT-2 NLP Agent
Created: {created_at}
Author: {author}

Original Instructions:
{original_instructions}
"""

import json
from opentrons import protocol_api

metadata = {{
    'protocolName': '{name}',
    'author': '{author}',
    'description': '{description}',
    'apiLevel': '{api_level}'
}}

{custom_labware_definitions}

def run(protocol: protocol_api.ProtocolContext):
    """Main protocol execution."""

    # ========================================
    # LABWARE SETUP
    # ========================================
{labware_setup}

    # ========================================
    # PIPETTE SETUP
    # ========================================
{pipette_setup}

    # ========================================
    # PROTOCOL STEPS
    # ========================================
{protocol_steps}

    # Protocol complete
    protocol.comment("Protocol complete!")
'''

    def generate(self, protocol: Protocol) -> str:
        """
        Generate Python protocol code from a Protocol object.

        Args:
            protocol: Protocol object containing all configuration and operations

        Returns:
            Python code string for the protocol
        """
        # Generate custom labware definitions
        custom_labware_defs = self._generate_custom_labware_definitions(protocol)

        # Generate labware setup (with custom labware support)
        labware_setup = self._generate_labware_setup(protocol.labware, protocol.metadata)

        # Generate pipette setup
        pipette_setup = self._generate_pipette_setup(protocol.pipettes)

        # Generate protocol steps
        protocol_steps = self._generate_protocol_steps(protocol.operations)

        # Format original instructions
        original_instructions = "\n".join(
            f"  - {instr}" for instr in protocol.original_instructions
        ) if protocol.original_instructions else "  (None provided)"

        # Fill template
        code = self.PROTOCOL_TEMPLATE.format(
            name=protocol.name,
            description=protocol.description or "No description provided",
            created_at=protocol.created_at.strftime("%Y-%m-%d %H:%M:%S"),
            author=protocol.author,
            api_level=protocol.api_level,
            original_instructions=original_instructions,
            custom_labware_definitions=custom_labware_defs,
            labware_setup=labware_setup,
            pipette_setup=pipette_setup,
            protocol_steps=protocol_steps,
        )

        return code

    def _generate_custom_labware_definitions(self, protocol: Protocol) -> str:
        """Generate custom labware definition code."""
        custom_labware = protocol.metadata.get('custom_labware', {})
        if not custom_labware:
            return "# No custom labware definitions"

        lines = ["# Custom labware definitions (3D printed / non-standard)"]
        lines.append("CUSTOM_LABWARE = {")

        for name, definition in custom_labware.items():
            # Format JSON with proper indentation
            json_str = json.dumps(definition, indent=4)
            # Indent each line for the dict
            indented = "\n".join("    " + line for line in json_str.split("\n"))
            lines.append(f'    "{name}": {json_str},')

        lines.append("}")
        lines.append("")
        lines.append("")
        lines.append("def load_custom_labware(protocol, name, slot):")
        lines.append('    """Load custom labware from embedded definition."""')
        lines.append("    if name not in CUSTOM_LABWARE:")
        lines.append(f'        raise ValueError(f"Unknown custom labware: {{name}}")')
        lines.append("    return protocol.load_labware_from_definition(CUSTOM_LABWARE[name], slot)")

        return "\n".join(lines)

    def _generate_labware_setup(self, labware: List[LabwareConfig], metadata: Dict = None) -> str:
        """Generate labware setup code."""
        if not labware:
            return "    # No labware configured - add labware here\n    pass"

        metadata = metadata or {}
        custom_labware_names = set(metadata.get('custom_labware', {}).keys())

        lines = []
        for lw in labware:
            if lw.name in custom_labware_names:
                # Use custom labware loader
                lines.append(
                    f"    {lw.name} = load_custom_labware(protocol, '{lw.name}', {lw.slot})"
                )
            else:
                # Standard labware
                lines.append(
                    f"    {lw.name} = protocol.load_labware('{lw.labware_type}', {lw.slot})"
                )
        return "\n".join(lines)

    def _generate_pipette_setup(self, pipettes: List[PipetteConfig]) -> str:
        """Generate pipette setup code."""
        if not pipettes:
            return "    # No pipettes configured - add pipettes here\n    pass"

        lines = []
        for pip in pipettes:
            tip_rack_arg = f", tip_racks=[{pip.tip_rack}]" if pip.tip_rack else ""
            lines.append(
                f"    {pip.name} = protocol.load_instrument('{pip.pipette_type}', '{pip.mount}'{tip_rack_arg})"
            )
        return "\n".join(lines)

    def _generate_protocol_steps(self, operations: List[Operation]) -> str:
        """Generate protocol step code."""
        if not operations:
            return "    # No operations defined\n    pass"

        lines = []
        for i, op in enumerate(operations, 1):
            # Add step comment
            if op.description:
                lines.append(f"\n    # Step {i}: {op.description}")
            else:
                lines.append(f"\n    # Step {i}: {op.type.value}")

            # Add operation code
            code = op.to_python()
            lines.append(f"    {code}")

        return "\n".join(lines)

    def save(self, protocol: Protocol, filepath: str):
        """
        Save protocol to a Python file.

        Args:
            protocol: Protocol object to save
            filepath: Path to save the file
        """
        code = self.generate(protocol)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(code)

    def generate_preview(self, protocol: Protocol) -> str:
        """
        Generate a human-readable preview of the protocol.

        Returns a summary without full code, useful for user confirmation.
        """
        lines = [
            f"Protocol: {protocol.name}",
            f"Description: {protocol.description or 'None'}",
            "",
            "Labware:",
        ]

        if protocol.labware:
            for lw in protocol.labware:
                lines.append(f"  - {lw.name}: {lw.labware_type} in slot {lw.slot}")
        else:
            lines.append("  (No labware configured)")

        lines.append("")
        lines.append("Pipettes:")

        if protocol.pipettes:
            for pip in protocol.pipettes:
                lines.append(f"  - {pip.name}: {pip.pipette_type} on {pip.mount} mount")
        else:
            lines.append("  (No pipettes configured)")

        lines.append("")
        lines.append(f"Operations ({len(protocol.operations)} steps):")

        for i, op in enumerate(protocol.operations, 1):
            desc = op.description or op.type.value
            lines.append(f"  {i}. {desc}")
            if op.params:
                param_str = ", ".join(f"{k}={v}" for k, v in op.params.items())
                lines.append(f"     Parameters: {param_str}")

        return "\n".join(lines)

    def generate_workflow_json(self, protocol: Protocol, version: str = "1.0") -> Dict[str, Any]:
        """
        Generate workflow JSON in the standard format for cross-platform import.

        Args:
            protocol: Protocol object to convert
            version: Workflow version string

        Returns:
            Dictionary in workflow JSON format
        """
        # Build setup phase with labware and pipettes
        setup_steps = []
        step_counter = 1

        # Add pipette setup
        for pip in protocol.pipettes:
            setup_steps.append({
                "step_id": f"setup_{step_counter:03d}",
                "action": "robot.load_pipettes",
                "params": {
                    "pipette_type": pip.pipette_type,
                    "mount": pip.mount,
                    "tip_rack": pip.tip_rack
                },
                "description": f"Load {pip.pipette_type} on {pip.mount} mount"
            })
            step_counter += 1

        # Add labware setup
        for lw in protocol.labware:
            setup_steps.append({
                "step_id": f"setup_{step_counter:03d}",
                "action": "robot.load_labware",
                "params": {
                    "slot": lw.slot,
                    "labware": lw.labware_type,
                    "name": lw.name
                },
                "description": f"Load {lw.labware_type} in slot {lw.slot}"
            })
            step_counter += 1

        # Build execution phase with operations
        execution_steps = []
        step_counter = 1

        for op in protocol.operations:
            action = self._operation_type_to_action(op.type)
            execution_steps.append({
                "step_id": f"exec_{step_counter:03d}",
                "action": action,
                "params": op.params,
                "description": op.description or f"{op.type.value} operation"
            })
            step_counter += 1

        # Construct full workflow
        workflow = {
            "workflow_name": protocol.name,
            "version": version,
            "description": protocol.description or "Generated by OT-2 NLP Agent",
            "metadata": {
                "created_at": protocol.created_at.isoformat(),
                "author": protocol.author,
                "api_level": protocol.api_level,
                "original_instructions": protocol.original_instructions
            },
            "phases": [
                {
                    "phase_name": "setup",
                    "description": "Initialize hardware and load labware",
                    "steps": setup_steps
                },
                {
                    "phase_name": "execution",
                    "description": "Execute protocol steps",
                    "steps": execution_steps
                }
            ]
        }

        return workflow

    def _operation_type_to_action(self, op_type: OperationType) -> str:
        """Map operation type to action string."""
        action_map = {
            OperationType.ASPIRATE: "robot.aspirate",
            OperationType.DISPENSE: "robot.dispense",
            OperationType.TRANSFER: "robot.transfer",
            OperationType.PICK_UP_TIP: "robot.pick_up_tip",
            OperationType.DROP_TIP: "robot.drop_tip",
            OperationType.MIX: "robot.mix",
            OperationType.PAUSE: "robot.pause",
            OperationType.WAIT: "wait",
            OperationType.BLOWOUT: "robot.blow_out",
            OperationType.HOME: "robot.home",
        }
        return action_map.get(op_type, f"robot.{op_type.value}")

    def save_workflow_json(self, protocol: Protocol, filepath: str, version: str = "1.0"):
        """
        Save protocol as workflow JSON file.

        Args:
            protocol: Protocol object to save
            filepath: Path to save the JSON file
            version: Workflow version string
        """
        workflow = self.generate_workflow_json(protocol, version)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(workflow, f, indent=2, ensure_ascii=False)

    def to_json(self, protocol: Protocol) -> str:
        """
        Generate JSON string of workflow.

        Args:
            protocol: Protocol object to convert

        Returns:
            JSON string
        """
        workflow = self.generate_workflow_json(protocol)
        return json.dumps(workflow, indent=2, ensure_ascii=False)
