RUN_STATUS_REQUESTED = "requested"
RUN_STATUS_COMPILED = "compiled"
RUN_STATUS_AWAITING_APPROVAL = "awaiting_approval"
RUN_STATUS_SCHEDULED = "scheduled"
RUN_STATUS_RUNNING = "running"
RUN_STATUS_SUCCEEDED = "succeeded"
RUN_STATUS_FAILED = "failed"
RUN_STATUS_ABORTED = "aborted"
RUN_STATUS_REJECTED = "rejected"

STEP_STATUS_PENDING = "pending"
STEP_STATUS_RUNNING = "running"
STEP_STATUS_SUCCEEDED = "succeeded"
STEP_STATUS_FAILED = "failed"
STEP_STATUS_SKIPPED = "skipped"

TERMINAL_RUN_STATUSES = {
    RUN_STATUS_SUCCEEDED,
    RUN_STATUS_FAILED,
    RUN_STATUS_ABORTED,
    RUN_STATUS_REJECTED,
}
